CREATE TABLE TBL_BOOKS (
    ID NUMBER PRIMARY KEY, -- COLUMN LEVEL CONSTRAINT
    TITLE VARCHAR(255),
    PRICE NUMBER(10, 2),
    PAGES NUMBER,
    PUBLISHER VARCHAR(255),
    AUTHOR VARCHAR(255)
);

DROP TABLE TBL_BOOKS;

CREATE TABLE TBL_BOOKS (
    ID NUMBER,
    TITLE VARCHAR(255),
    PRICE NUMBER(10, 2),
    PAGES NUMBER,
    PUBLISHER VARCHAR(255),
    AUTHOR VARCHAR(255),
    CONSTRAINT PK_TBL_BOOKS PRIMARY KEY (ID) -- TABLE LEVEL CONSTRAINT
);

CREATE TABLE TBL_BOOKS (
    ID NUMBER,
    TITLE VARCHAR(255),
    PRICE NUMBER(10, 2),
    PAGES NUMBER,
    PUBLISHER VARCHAR(255),
    AUTHOR VARCHAR(255)
);

ALTER TABLE TBL_BOOKS ADD PRIMARY KEY (ID);
ALTER TABLE TBL_BOOKS DROP PRIMARY KEY;
ALTER TABLE TBL_BOOKS ADD CONSTRAINT PK_TBL_BOOKS PRIMARY KEY (ID);


CREATE TABLE TBL_BOOKS (
    ID NUMBER,
    TITLE VARCHAR(255) NOT NULL,
    PRICE NUMBER(10, 2),
    PAGES NUMBER,
    PUBLISHER VARCHAR(255) NOT NULL,
    AUTHOR VARCHAR(255),
    CONSTRAINT CHK_TBL_BOOKS_PRICE CHECK (PRICE>=0), -- TABLE LEVEL CONSTRAINT
    CONSTRAINT PK_TBL_BOOKS PRIMARY KEY (ID) -- TABLE LEVEL CONSTRAINT
);


-- Sequence of values must match the sequence of columns in the table
INSERT INTO TBL_BOOKS VALUES (1, 'ORACLE MADE EASY', 399, 290, 'BPB PUBLICATIONS', 'VINOD KUMAR');
INSERT INTO TBL_BOOKS (ID, PRICE, TITLE, PUBLISHER) VALUES (2, 350, 'LET US C', 'BPB PUBLICATIONS');
INSERT INTO TBL_BOOKS (ID, PRICE, TITLE, PUBLISHER, AUTHOR) VALUES (3, 750, 'C++ UNLEASHED', 'SAMS', 'JESSY LIBERTY');

ALTER TABLE TBL_BOOKS ADD CONSTRAINT CHK_TBL_BOOKS_PAGES CHECK (PAGES>0);

-- DURING UPDATE, IF THE WHERE CONDITION IS OMITTED, THEN ALL THE RECORDS
-- IN THE TABLE WILL BE UPDATED. (SAME APPLIES TO THE DELETE COMMAND AS WELL)
UPDATE TBL_BOOKS SET PAGES=290 WHERE ID=1;
UPDATE TBL_BOOKS SET PAGES=150, AUTHOR='YASHWANT KANITKAR' WHERE ID=2;


ALTER TABLE TBL_BOOKS RENAME COLUMN PAGES TO PAGE_COUNT;
ALTER TABLE TBL_BOOKS ADD BOOK_TYPE VARCHAR(50) DEFAULT 'PAPER BACK';
ALTER TABLE TBL_BOOKS MODIFY AUTHOR VARCHAR(100);
RENAME BOOKS TO TBL_BOOKS;

SELECT * FROM TBL_BOOKS;


CREATE TABLE TBL_CATEGORIES(
    CATEGORY_ID NUMBER PRIMARY KEY,
    CATEGORY_NAME VARCHAR(200)
);

INSERT INTO TBL_CATEGORIES VALUES (10, 'BEVERAGES');
INSERT INTO TBL_CATEGORIES VALUES (20, 'CONDIMENTS');

CREATE TABLE TBL_PRODUCTS(
    PRODUCT_ID NUMBER PRIMARY KEY,
    PRODUCT_NAME VARCHAR(100),
    UNIT_PRICE NUMBER(10,2),
    CATEGORY_ID NUMBER -- REFERENCES TBL_CATEGORIES
    -- CONSTRAINT FK_PRODUCTS_CATEGORIES FOREIGN KEY (CATEGORY_ID) REFERENCES TBL_CATEGORIES;
);

INSERT INTO TBL_PRODUCTS VALUES (1, 'CHAI', 18.2, 10);
INSERT INTO TBL_PRODUCTS VALUES (2, 'CHANG', 23.4, 10);
INSERT INTO TBL_PRODUCTS VALUES (3, 'MASALA TEA', 33.4, 10);

-- CATEGORY 40 DOES NOT EXIST IN THE CATEGORIES TABLE
INSERT INTO TBL_PRODUCTS VALUES (4, 'APPLE MAGIC MOUSE', 8500, 40);


DELETE FROM TBL_CATEGORIES WHERE CATEGORY_ID=10;
COMMIT;
UPDATE TBL_PRODUCTS SET CATEGORY_ID=10 WHERE CATEGORY_ID=30;


ALTER TABLE TBL_PRODUCTS
ADD CONSTRAINT FK_PRODUCTS_CATEGORIES
FOREIGN KEY (CATEGORY_ID)
REFERENCES TBL_CATEGORIES;
-- ON DELETE SET NULL; 
-- ON DELETE CASCADE;

ALTER TABLE TBL_PRODUCTS DROP CONSTRAINT FK_PRODUCTS_CATEGORIES;




SELECT *FROM TBL_CATEGORIES;
SELECT * FROM TBL_PRODUCTS;




